name: Auto tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - danger_test
          - safety_test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install chrome
        run: sudo apt-get install google-chrome-stable
      - name: Setup requirements
        run: pip install -r requirements.txt
      - name: Run danger tests
        if: "github.event.inputs.deployment_target == 'danger_test'"
        run: pytest tests -m danger
      - name: Run safety tests
        if: "github.event.inputs.deployment_target == safe_test"
        run: pytest tests -m safe